# Generated by Django 3.2.4 on 2021-06-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='discipline',
        ),
        migrations.AddField(
            model_name='entry',
            name='disciplines',
            field=models.ManyToManyField(to='image_input.Discipline', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='year',
            field=models.CharField(choices=[('2016, 1s', '2016, 1s'), ('2016, 2s', '2016, 2s'), ('2017, 1s', '2017, 1s'), ('2017, 2s', '2017, 2s'), ('2018, 1s', '2018, 1s'), ('2018, 2s', '2018, 2s'), ('2019, 1s', '2019, 1s'), ('2019, 2s', '2019, 2s'), ('2020, 1s', '2020, 1s'), ('2020, 2s', '2020, 2s'), ('2021, 1s', '2021, 1s'), ('2021, 2s', '2021, 2s')], max_length=32, verbose_name='Год'),
        ),
    ]
