# Generated by Django 3.2.4 on 2021-06-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_input', '0002_auto_20210618_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='type',
            field=models.CharField(choices=[('LEC', 'Лекция'), ('PRC', 'Практика')], default='PRC', max_length=3, verbose_name='Тип занятия'),
            preserve_default=False,
        ),
    ]
